import React, { StrictMode } from 'react'
import { describe, expect, it, vi } from 'vitest'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { SessionProvider } from '../src/auth/SessionProvider.jsx'
import { ApiError } from '../src/api/errors.js'
import { RagLayout } from '../src/features/rag/state.jsx'
import { RagDocumentPage, RagQueryPage } from '../src/features/rag/pages.jsx'
import { RagStateBanner } from '../src/features/rag/components.jsx'

function dtoFixture(state = 'EVIDENCIA_SUFICIENTE') {
  const metadata = { fragment_id: '33333333-3333-4333-8333-333333333333', document_id: 'DOC-SINTETICO', document_name: 'Documento sintético', document_type: 'PDF', document_date: null, page_start: null, page_end: null, section: null, clause: null }
  const enough = state === 'EVIDENCIA_SUFICIENTE'
  return { operation_id: '11111111-1111-4111-8111-111111111111', correlation_id: '22222222-2222-4222-8222-222222222222', state, operation_status: 'COMPLETED', generation_status: enough ? 'SUCCEEDED' : 'NOT_REQUESTED', generated_response: enough ? 'Respuesta sintética [E1].' : null, safe_result_message: enough ? null : 'Mensaje seguro sintético.', context_reference_id: null, fragments: enough || state === 'EVIDENCIA_INSUFICIENTE' ? [{ ...metadata, fragment_text: 'Texto sintético autorizado.', usage: enough ? 'EVIDENCE' : 'REFERENCE' }] : [], citations: enough ? [{ handle: 'E1', ...metadata }] : [] }
}

function mount({ dto = dtoFixture(), path = '/consulta', request, revalidate = async () => true } = {}) {
  const client = { request: request || vi.fn(async () => dto) }
  const listeners = new Set()
  let snapshot = { status: 'authenticated', principal: { id: '11111111-1111-4111-8111-111111111111', username: 'cuenta-sintetica', roles: ['JURIDICO'] }, generation: 1 }
  const manager = { client, getSnapshot: () => snapshot, subscribe: (callback) => { listeners.add(callback); return () => listeners.delete(callback) }, restore: vi.fn(), revalidate: vi.fn(revalidate), invalidate: () => { snapshot = { status: 'anonymous', principal: null, generation: 2 }; for (const callback of listeners) callback(snapshot) } }
  render(<StrictMode><SessionProvider manager={manager}><MemoryRouter initialEntries={[path]}><Routes><Route element={<RagLayout />}><Route path="/consulta" element={<RagQueryPage />} /><Route path="/documentos" element={<RagDocumentPage />} /></Route></Routes></MemoryRouter></SessionProvider></StrictMode>)
  return manager
}
async function query() { await userEvent.type(await screen.findByLabelText('Consulta en lenguaje natural'), 'Consulta sintética'); await userEvent.click(screen.getByRole('button', { name: 'Consultar' })) }

describe('SRS_REQUIRED: consulta y visor autorizados', () => {
  it.each(['EVIDENCIA_SUFICIENTE', 'EVIDENCIA_INSUFICIENTE', 'SIN_EVIDENCIA', 'SIN_AUTORIZACION'])('presenta exactamente el estado %s', async (state) => { mount({ dto: dtoFixture(state) }); await query(); expect(await screen.findByText({ EVIDENCIA_SUFICIENTE: 'Evidencia suficiente', EVIDENCIA_INSUFICIENTE: 'Evidencia insuficiente', SIN_EVIDENCIA: 'Sin evidencia', SIN_AUTORIZACION: 'Sin autorización' }[state])).toBeVisible(); if (state !== 'EVIDENCIA_SUFICIENTE') expect(screen.queryByText('Respuesta sintética [E1].')).not.toBeInTheDocument() })
  it('consulta y visor comparten fragmento solo en memoria y revalidan identidad al navegar', async () => { const manager = mount(); await query(); await userEvent.click(await screen.findByRole('link', { name: 'Ver fragmento en visor' })); expect(await screen.findByRole('heading', { name: 'Visor documental' })).toBeVisible(); expect(screen.getByText('Texto sintético autorizado.')).toBeVisible(); expect(screen.getByText('No disponible')).toBeVisible(); expect(manager.revalidate.mock.calls.length).toBeGreaterThan(1); expect(manager.client.request).toHaveBeenCalledTimes(1) })
  it('recarga o deep link al visor sin resultado muestra vacío y no consulta', async () => { const manager = mount({ path: '/documentos?fragment_id=33333333-3333-4333-8333-333333333333' }); expect(await screen.findByText('No hay un fragmento disponible')).toBeVisible(); expect(manager.client.request).not.toHaveBeenCalled() })
  it('errores provider se muestran aparte y preservan el texto recuperado', async () => { const dto = dtoFixture(); dto.operation_status = 'FAILED'; dto.generation_status = 'FAILED'; dto.generated_response = null; mount({ dto }); await query(); expect(await screen.findByText('Evidencia suficiente')).toBeVisible(); expect(screen.getByRole('alert')).toHaveTextContent('El servicio no está disponible'); expect(screen.getByText('Texto sintético autorizado.')).toBeVisible(); expect(screen.queryByText('Sin evidencia')).not.toBeInTheDocument() })
  it('contenido malicioso se renderiza como texto sin HTML ni atributos ejecutables', async () => { const dto = dtoFixture(); dto.generated_response = '<img src=x onerror=alert(1)> [E1]'; dto.fragments[0] = { ...dto.fragments[0], fragment_text: '<script>alert(1)</script>' }; mount({ dto }); await query(); expect(await screen.findByText('<img src=x onerror=alert(1)> [E1]')).toBeVisible(); expect(screen.getByText('<script>alert(1)</script>')).toBeVisible(); expect(document.querySelector('script')).toBeNull(); expect(document.querySelector('[onerror]')).toBeNull() })
  it('HTTP403 elimina evidencia anterior y no revela respuesta de error', async () => { const request = vi.fn().mockResolvedValueOnce(dtoFixture()).mockRejectedValueOnce(new ApiError(403)); mount({ request }); await query(); await screen.findByText('Texto sintético autorizado.'); await userEvent.click(screen.getByRole('button', { name: 'Consultar' })); expect(await screen.findByRole('alert')).toHaveTextContent('Sin autorización'); expect(screen.queryByText('Texto sintético autorizado.')).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Reintentar la misma operación' })).not.toBeInTheDocument() })
  it('HTTP401 elimina evidencia anterior y no permite reintentar la operación protegida', async () => { const request = vi.fn().mockResolvedValueOnce(dtoFixture()).mockRejectedValueOnce(new ApiError(401)); mount({ request }); await query(); await screen.findByText('Texto sintético autorizado.'); await userEvent.click(screen.getByRole('button', { name: 'Consultar' })); expect(await screen.findByRole('alert')).toHaveTextContent('Credenciales o sesión no válidas'); expect(screen.queryByText('Texto sintético autorizado.')).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Reintentar la misma operación' })).not.toBeInTheDocument() })
  it('cambio ACL con sesión invalidada antes del visor retira el fragmento', async () => { let allowed = true; const manager = mount({ revalidate: async () => allowed }); await query(); await screen.findByText('Texto sintético autorizado.'); allowed = false; await userEvent.click(screen.getByRole('link', { name: 'Ver fragmento en visor' })); expect(await screen.findByText('No hay un fragmento disponible')).toBeVisible(); expect(screen.queryByText('Texto sintético autorizado.')).not.toBeInTheDocument(); expect(manager.client.request).toHaveBeenCalledTimes(1) })
  it('blur borra consulta y evidencia sin repetir la solicitud al recuperar foco', async () => { const manager = mount(); await query(); await screen.findByText('Texto sintético autorizado.'); fireEvent(window, new Event('blur')); expect(screen.queryByText('Texto sintético autorizado.')).not.toBeInTheDocument(); expect(screen.getByLabelText('Consulta en lenguaje natural')).toHaveValue(''); fireEvent(window, new Event('focus')); expect(manager.client.request).toHaveBeenCalledTimes(1) })
  it('referencia contextual opcional se envía sin filtros ni texto en URL', async () => { const manager = mount({ path: '/consulta?context_reference_id=44444444-4444-4444-8444-444444444444&entity=Privado&query=Privado' }); await query(); await screen.findByText('Texto sintético autorizado.'); expect(manager.client.request.mock.calls[0][1].body).toEqual({ query: 'Consulta sintética', context_reference_id: '44444444-4444-4444-8444-444444444444' }); expect(screen.getByText(/No constituye evidencia/)).toBeVisible() })
  it('retry utiliza la identidad anterior y consulta explícita crea identidad nueva', async () => { const request = vi.fn().mockRejectedValueOnce(new ApiError(0, { uncertain: true })).mockResolvedValue(dtoFixture()); mount({ request }); await query(); await userEvent.click(await screen.findByRole('button', { name: 'Reintentar la misma operación' })); await screen.findByText('Texto sintético autorizado.'); expect(request.mock.calls[0][1].headers['Idempotency-Key']).toBe(request.mock.calls[1][1].headers['Idempotency-Key']); await userEvent.click(screen.getByRole('button', { name: 'Consultar' })); await waitFor(() => expect(request).toHaveBeenCalledTimes(3)); expect(request.mock.calls[2][1].headers['Idempotency-Key']).not.toBe(request.mock.calls[1][1].headers['Idempotency-Key']) })
  it('nunca escribe consulta o evidencia en storage', async () => { const local = vi.spyOn(Storage.prototype, 'setItem'); mount(); await query(); await screen.findByText('Texto sintético autorizado.'); expect(local).not.toHaveBeenCalled(); local.mockRestore() })
})
describe('ROBUSTNESS: forma segura y accesibilidad', () => {
  it('el banner no usa color como único estado', () => { render(<RagStateBanner state="SIN_AUTORIZACION" />); expect(screen.getByRole('status')).toHaveTextContent('Sin autorización') })
  it('denegación durante revalidación no abre visor ni dispara POST automático', async () => { const manager = mount({ path: '/documentos', revalidate: async () => false }); expect(await screen.findByText('No hay un fragmento disponible')).toBeVisible(); expect(manager.client.request).not.toHaveBeenCalled() })
  it('rechaza ID de visor desconocido sin devolver otros fragmentos', async () => { const manager = mount({ path: '/documentos?fragment_id=invalido' }); expect(await screen.findByText('No hay un fragmento disponible')).toBeVisible(); expect(manager.client.request).not.toHaveBeenCalled() })
})
