import { describe, expect, it } from 'vitest'
import { formatDecimal, formatValue, formatDate, formatTimestamp, validDate } from '../src/shared/formatters.js'
import { readQuery, writeQuery } from '../src/shared/query.js'
import { can, capabilitiesFor, validatePrincipal } from '../src/auth/permissions.js'
describe('SRS_REQUIRED: datos y permisos de presentación', () => {
  it('no convierte ausencia ni No disponible a cero', () => { expect(formatValue(null, 'DISPONIBLE')).toBe('No disponible'); expect(formatValue('0', 'NO_DISPONIBLE')).toBe('No disponible'); expect(formatValue('0', 'DISPONIBLE')).toBe('0') })
  it('conserva decimales textuales y cifras grandes sin redondear', () => { expect(formatDecimal('9007199254740993.0100')).toBe('9,007,199,254,740,993.0100'); expect(formatDecimal('-1234.50', { prefix: '$' })).toBe('$-1,234.50') })
  it('aplica unión multirrol y default deny sin claims JWT', () => { const principal = { roles: ['JURIDICO', 'ANALISTA'] }; expect(can(principal, 'ingest.upload')).toBe(true); expect(can(principal, 'role.assign')).toBe(false); expect(can({ roles: ['DESCONOCIDO'] }, 'dashboard.read')).toBe(false); expect(can(null, 'document.query')).toBe(false); expect(capabilitiesFor({ roles: ['TI'] }).has('audit.delete')).toBe(false) })
  it('valida identidad, evita rol no textual y no confía en capabilities suministradas', () => { const principal = validatePrincipal({ id: '11111111-1111-4111-8111-111111111111', username: 'sintetico', roles: ['JURIDICO'], capabilities: ['role.assign'] }); expect(can(principal, 'role.assign')).toBe(false); expect(validatePrincipal({ ...principal, roles: [1] })).toBeNull(); expect(validatePrincipal({ ...principal, id: '------------------------------------' })).toBeNull() })
})
describe('ROBUSTNESS: formatos y URL', () => {
  it('no acepta valores numéricos ambiguos', () => { expect(formatDecimal('Infinity')).toBe('No disponible'); expect(formatDecimal('1e3')).toBe('No disponible') })
  it('conserva el día natural sin desplazamiento de timezone', () => { expect(formatDate('2030-01-01')).toBe('01/01/2030'); expect(validDate('2030-02-30')).toBe(false); expect(formatDate(null)).toBe('—'); expect(formatTimestamp('2030-01-01T12:00:00Z')).toContain('UTC'); expect(formatTimestamp('2030-01-01T12:00:00')).toBe('—') })
  it('no transforma fechas u horas imposibles en timestamps aparentemente válidos', () => { for (const value of ['2030-02-30T12:00:00Z', '2030-01-01T24:00:00Z', '2030-01-01T12:60:00Z', '2030-01-01T12:00:60Z', '2030-01-01T12:00:00+01:60']) expect(formatTimestamp(value)).toBe('—'); expect(formatTimestamp('2030-01-01T12:00:00.123456-06:00')).toContain('UTC') })
  it('solo persiste query params permitidos y válidos', () => { const rules = { entity: (value) => ['Área norte', 'Área sur'].includes(value), period: (value) => ['last_6_months'].includes(value) }; expect(readQuery('?entity=%C3%81rea+norte&password=oculta&period=incorrecto', rules)).toEqual({ entity: 'Área norte' }); expect(writeQuery({ period: 'last_6_months', entity: 'Área norte', query: 'consulta sensible' }, rules)).toBe('entity=%C3%81rea+norte&period=last_6_months') })
  it('rechaza claves duplicadas y respeta navegación Back/Forward', () => { const rules = { period: (value) => ['a', 'b'].includes(value) }; expect(readQuery('?period=a&period=b', rules)).toEqual({}); window.history.replaceState(null, '', '/?period=a'); const first = readQuery(window.location.search, rules); window.history.pushState(null, '', '/?period=b'); expect(first.period).toBe('a'); expect(readQuery(window.location.search, rules).period).toBe('b') })
})
